name: Build pushed changes

# on:
#  pull_request:
#   types:
#     - closed
#   branches:
#     - master
#  push:
#    branches:
#     - master

on:
  push:
    branches:
      - main

jobs:
 Build:
   runs-on: ubuntu-latest
   steps:
   
   - name: Set up Node.js
     uses: actions/setup-node@v2
     with:
       node-version: '18'

  #  - name: Checkout to branch
  #    uses: actions/checkout@v4
  #    with:
  #      ref: master

  #  - name: Get package info
  #    id: package
  #    uses: codex-team/action-nodejs-package-info@v1.1

   - name: Install dependencies
     run: cd server && npm install

   - name: Build
     run: cd server && npm install

   - name: Check branch changes
     id: changes
     uses: UnicornGlobal/has-changes-action@v1.0.11

   - name: Commit
     if: steps.changes.outputs.changed == 1
     run: |
         git config user.name github-actions
         git config user.email github-actions@medias.com.ua
         git add .
         git commit -m "Building ${{ steps.package.outputs.version }}"
         git push