
name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: cd client && npm install

    - name: Commit
      run: |
          git config user.name github-actions
          git config user.email github-actions@medias.com.ua
          git add .
          git commit -m "Building ${{ steps.package.outputs.version }}"
          git push